import { Router } from "express";
import authMiddleware from "../middlewares/auth.middleware";
import myCourse from "../modules/courseDomain/course/course.me.routes";
import courseCategoryRoutes from "../modules/courseDomain/courseCategories/courseCategories.routes";
import coursePublishRoutes from "../modules/courseDomain/coursePublish/coursePublish.routes";
import enrollmentRoutes from "../modules/courseDomain/enrollment/enrollment.routes";
import learnRoutes from "../modules/courseDomain/learn/learn.routes";
import courseSectionRoutes from "../modules/courseDomain/sectionDomain/courseSection/courseSection.routes";
import courseForumRoutes from "../modules/courseDomain/sectionDomain/forum/courseForum.routes";
import forumRoutes from "../modules/courseDomain/sectionDomain/forum/forum.routes";
import lessonRoutes from "../modules/courseDomain/sectionDomain/lesson/lesson.routes";
import quizRoutes from "../modules/courseDomain/sectionDomain/quiz/quiz.routes";
import sectionItemRoutes from "../modules/courseDomain/sectionDomain/sectionItem/sectionItem.routes";
import myInvoiceRoutes from "../modules/invoice/invoice.me.routes";
import invoiceRoutes from "../modules/invoice/invoice.routes";
import notificationRoutes from "../modules/notification/notification.routes";
import orderRoutes from "../modules/order/order.routes";
import userRoutes from "../modules/users/users.routes";

const api = Router();

api.use(authMiddleware);
api.use("/user", userRoutes);
api.use("/me/courses", myCourse);
api.use("/me/forum", forumRoutes);
api.use("/me/courses/:courseId/sections", courseSectionRoutes);
api.use("/me/courses/:courseId/sections/:sectionId/items", sectionItemRoutes);
api.use("/me/courses/:courseId/sections/:sectionId/items/:itemId/lesson", lessonRoutes);
api.use("/me/courses/:courseId/sections/:sectionId/items/:itemId/quiz", quizRoutes);
api.use("/me/courses/:courseId/sections/:sectionId/items/:itemId/forum", courseForumRoutes);
api.use("/me/enrollments", enrollmentRoutes);
api.use("/me/learn/:courseSlug", learnRoutes);
api.use("/courses/publish-requests", coursePublishRoutes);
api.use("/course-categories", courseCategoryRoutes);
api.use("/me/invoices", myInvoiceRoutes);
api.use("/me/notifications", notificationRoutes);
api.use("/invoices", invoiceRoutes);
api.use("/orders", orderRoutes);
export default api;
